name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20

      # ESLint must be in `package.json`
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint Codebase
        run: yarn workspaces foreach -A run lint
